name: CI Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-app:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run application
        run: python -m manage runserver

  run-tests:
    runs-on: ubuntu-latest

    needs: run-app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Go to tests directory
        working-directory: tests/
        run: npm ci

      - name: Install playwright browsers
        run: npx playwright install

      - name: Run tests
        working-directory: tests/
        run: npm test